language: r
cache: packages
warnings_are_errors: true

r_github_packages:
  - jimhester/covr
  - hughparsonage/ReporteRsjars
  - hughparsonage/ReporteRs

after_success:
  - Rscript -e 'covr::codecov(function_exclusions = "install")'
