---
title: "Grattan Chartbook"
author: "Hugh Parsonage"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{grattanCharts}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ggplot2)
library(grattanCharts)
library(scales)
library(data.table)
library(grattan)
```


```{r worm}
dt <- 
  data.table(x = rep(2009:2019, times = 6),
             fy = c("Actual", 2012:2016))
setkey(dt, fy, x)
dt[fy == "Actual", 
   y := c(-2, -4.3, -3.5, -2.9, -1.1, -3, NA, NA, NA, NA, NA)]
dt[fy == "2012", 
   y := c(NA, -4.3, -3.6, -1.0, 0.1, 0.1, 0.3, NA, NA, NA, NA)]
dt[fy == "2013", 
   y := c(NA, NA, -3.5, -3, 0.1, 0.1, 0.2, 0.4, NA, NA, NA)]
dt[fy == "2014", 
   y := c(NA, NA, NA, NA, -1.2, -1, -0.5, 0, 0.5, NA, NA)]
dt[fy == "2015",
   y := c(NA, NA, NA, NA, NA, -3, -1.9, -1, -0.5, -0.1, NA)]
dt[fy == "2016", 
   y := c(NA, NA, NA, NA, NA, -3, -2.5, -2, -1.5, -1, -0.5)]

grplot(dt, aes(x = x, y = y, color = fy, group = fy), reverse = TRUE) +
  geom_line(na.rm = TRUE)
```


